--- 
- hosts: all
  gather_facts: no
  become: true
  tasks:
  - name: install the httpd server
    yum:
     name: httpd
     state: latest
  - name: copy the index.html
    template:
     src: index.html
     dest: /var/www/html/index.html
  - name: restart the httpd server
    service:
     name: httpd
     state: restarted
     
...
